export const GLOBAL_CUMULATIVE = 'GLOBAL_CUMULATIVE';
export const COUNTRY_CUMULATIVE = 'COUNTRY_CUMULATIVE';
export const GLOBAL_TIMELINE = 'GLOBAL_TIMELINE';
export const COUNTRY_TIMELINE = 'COUNTRY_TIMELINE';
